import type { AppState } from "./types";

const now = new Date();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 86400000).toISOString();
const daysFromNow = (d: number) =>
  new Date(now.getTime() + d * 86400000).toISOString();

export const SEED_DATA: AppState = {
  users: [
    {
      id: "buyer-1",
      name: "Jonathan Park",
      email: "jonathan@stimulus.com",
      role: "buyer",
      organization: "Stimulus Procurement",
    },
    {
      id: "buyer-2",
      name: "Carlos Mendez",
      email: "carlos@stimulus.com",
      role: "buyer",
      organization: "Stimulus Procurement",
    },
    {
      id: "buyer-3",
      name: "Evren Aksoy",
      email: "evren@stimulus.com",
      role: "buyer",
      organization: "Stimulus Procurement",
    },
    {
      id: "supplier-1",
      name: "Alex Rivera",
      email: "alex@globaltech.io",
      role: "supplier",
      organization: "GlobalTech Solutions",
    },
    {
      id: "supplier-2",
      name: "Jordan Lee",
      email: "jordan@nexus-ind.com",
      role: "supplier",
      organization: "Nexus Industries",
      diversityTag: "MBE",
    },
    {
      id: "supplier-3",
      name: "Sam Patel",
      email: "sam@brightline.co",
      role: "supplier",
      organization: "Brightline Systems",
      diversityTag: "WBE",
    },
    {
      id: "supplier-4",
      name: "Maria Santos",
      email: "maria@apexlogistics.com",
      role: "supplier",
      organization: "Apex Logistics",
    },
    {
      id: "supplier-5",
      name: "David Kim",
      email: "david@greenleaf.co",
      role: "supplier",
      organization: "GreenLeaf Co",
      diversityTag: "SBE",
    },
    {
      id: "supplier-6",
      name: "Priya Sharma",
      email: "priya@meridiantech.io",
      role: "supplier",
      organization: "Meridian Tech",
      diversityTag: "MBE",
    },
    {
      id: "supplier-7",
      name: "Chris Wong",
      email: "chris@summitsolutions.com",
      role: "supplier",
      organization: "Summit Solutions",
    },
    {
      id: "supplier-8",
      name: "Taylor Brooks",
      email: "taylor@coastalpartners.com",
      role: "supplier",
      organization: "Coastal Partners",
    },
  ],
  currentUserId: "buyer-1",
  rfxRecords: [
    // RFI — Q&A Open (unanswered question)
    {
      id: "rfi-1",
      type: "RFI",
      title: "Cloud Infrastructure Capabilities Assessment",
      description:
        "Gather information on cloud infrastructure capabilities, security certifications, and migration experience from potential vendors.",
      status: "open",
      buyerId: "buyer-1",
      createdAt: daysAgo(14),
      updatedAt: daysAgo(10),
      dueDate: daysFromNow(7),
      publishedAt: daysAgo(10),
      questions: [
        { id: "q1", text: "Describe your cloud infrastructure architecture and supported regions.", required: true, type: "textarea" },
        { id: "q2", text: "List all security certifications (SOC 2, ISO 27001, etc.).", required: true, type: "textarea" },
        { id: "q3", text: "Do you support hybrid cloud deployments?", required: true, type: "yes_no" },
        { id: "q4", text: "Describe your experience with enterprise migration projects (>1000 VMs).", required: false, type: "textarea" },
      ],
      shortlistedSupplierIds: [],
    },
    // RFI — Closed
    {
      id: "rfi-2",
      type: "RFI",
      title: "Office Furniture Vendor Discovery",
      description: "Initial market research for ergonomic office furniture suppliers.",
      status: "closed",
      buyerId: "buyer-2",
      createdAt: daysAgo(45),
      updatedAt: daysAgo(5),
      dueDate: daysAgo(10),
      publishedAt: daysAgo(40),
      closedAt: daysAgo(5),
      closeNotes: "Review complete. GlobalTech and Nexus shortlisted for RFP phase.",
      shortlistedSupplierIds: ["supplier-1", "supplier-2"],
      convertedToRfpId: "rfp-6",
      questions: [
        { id: "q1", text: "What product lines do you offer for enterprise offices?", required: true, type: "textarea" },
        { id: "q2", text: "What is your typical lead time for bulk orders?", required: true, type: "text" },
      ],
    },
    // RFI — Draft (late draft — due date passed)
    {
      id: "rfi-3",
      type: "RFI",
      title: "Cybersecurity Services Landscape",
      description: "Draft RFI for cybersecurity managed services.",
      status: "draft",
      buyerId: "buyer-3",
      createdAt: daysAgo(30),
      updatedAt: daysAgo(1),
      dueDate: daysAgo(5),
      questions: [
        { id: "q1", text: "Describe your SOC capabilities and staffing model.", required: true, type: "textarea" },
      ],
      shortlistedSupplierIds: [],
    },
    // RFI — Published (ready to invite, no suppliers yet)
    {
      id: "rfi-4",
      type: "RFI",
      title: "Facilities Management Providers",
      description: "Market scan for facilities management and maintenance providers.",
      status: "published",
      buyerId: "buyer-1",
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
      dueDate: daysFromNow(21),
      publishedAt: daysAgo(1),
      questions: [
        { id: "q1", text: "Describe your facilities management service scope.", required: true, type: "textarea" },
        { id: "q2", text: "How many active contracts do you currently manage?", required: true, type: "text" },
      ],
      shortlistedSupplierIds: [],
    },
    // RFI — Responses (submissions received, no open Q&A)
    {
      id: "rfi-5",
      type: "RFI",
      title: "Print Services Vendor Survey",
      description: "Survey print and document management vendors for enterprise contract.",
      status: "open",
      buyerId: "buyer-2",
      createdAt: daysAgo(20),
      updatedAt: daysAgo(3),
      dueDate: daysFromNow(10),
      publishedAt: daysAgo(15),
      questions: [
        { id: "q1", text: "What print management platforms do you support?", required: true, type: "textarea" },
        { id: "q2", text: "Do you offer on-site service?", required: true, type: "yes_no" },
      ],
      shortlistedSupplierIds: [],
    },
    // RFQ — Submissions Open
    {
      id: "rfq-1",
      type: "RFQ",
      title: "Q2 Laptop Procurement",
      description: "Request for quotation on 150 business laptops with extended warranty.",
      status: "open",
      buyerId: "buyer-1",
      createdAt: daysAgo(7),
      updatedAt: daysAgo(5),
      dueDate: daysFromNow(14),
      publishedAt: daysAgo(5),
      lineItems: [
        { id: "li-1", description: "Business Laptop - 14\" Intel i7, 16GB RAM, 512GB SSD", quantity: 120, unit: "each", estimatedUnitPrice: 1200 },
        { id: "li-2", description: "Business Laptop - 15\" Intel i7, 32GB RAM, 1TB SSD", quantity: 30, unit: "each", estimatedUnitPrice: 1800 },
        { id: "li-3", description: "Extended 3-year warranty", quantity: 150, unit: "each", estimatedUnitPrice: 200 },
      ],
    },
    // RFQ — Awarded
    {
      id: "rfq-2",
      type: "RFQ",
      title: "Office Cleaning Services",
      description: "Annual contract for office cleaning across 3 locations.",
      status: "awarded",
      buyerId: "buyer-2",
      createdAt: daysAgo(60),
      updatedAt: daysAgo(3),
      dueDate: daysAgo(20),
      publishedAt: daysAgo(55),
      closedAt: daysAgo(3),
      awardedSupplierId: "supplier-3",
      awardNotes: "Best value proposal with strong references.",
      lineItems: [
        { id: "li-1", description: "Daily cleaning - HQ (15,000 sq ft)", quantity: 260, unit: "days" },
        { id: "li-2", description: "Weekly deep clean - Branch offices (2x)", quantity: 52, unit: "visits" },
      ],
    },
    // RFQ — Draft
    {
      id: "rfq-3",
      type: "RFQ",
      title: "Network Switch Replacement",
      description: "Draft RFQ for core network switch upgrade.",
      status: "draft",
      buyerId: "buyer-3",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
      dueDate: daysFromNow(21),
      lineItems: [
        { id: "li-1", description: "48-port managed switch", quantity: 8, unit: "each" },
      ],
    },
    // RFQ — Published
    {
      id: "rfq-4",
      type: "RFQ",
      title: "Conference Room AV Equipment",
      description: "Quote for AV equipment across 12 conference rooms.",
      status: "open",
      buyerId: "buyer-1",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      dueDate: daysFromNow(28),
      publishedAt: daysAgo(1),
      lineItems: [
        { id: "li-1", description: "4K display 75\"", quantity: 12, unit: "each" },
        { id: "li-2", description: "Video conferencing bar", quantity: 12, unit: "each" },
      ],
    },
    // RFQ — Q&A Open
    {
      id: "rfq-5",
      type: "RFQ",
      title: "Uniform & Apparel Supply",
      description: "Annual uniform supply for 500 field staff.",
      status: "open",
      buyerId: "buyer-3",
      createdAt: daysAgo(10),
      updatedAt: daysAgo(4),
      dueDate: daysFromNow(18),
      publishedAt: daysAgo(8),
      lineItems: [
        { id: "li-1", description: "Field jacket - winter", quantity: 500, unit: "each" },
        { id: "li-2", description: "Safety vest", quantity: 500, unit: "each" },
      ],
    },
    // RFQ — Closed
    {
      id: "rfq-6",
      type: "RFQ",
      title: "Parking Lot Resurfacing",
      description: "Resurface main campus parking lot.",
      status: "closed",
      buyerId: "buyer-2",
      createdAt: daysAgo(90),
      updatedAt: daysAgo(15),
      dueDate: daysAgo(30),
      publishedAt: daysAgo(80),
      closedAt: daysAgo(15),
      lineItems: [
        { id: "li-1", description: "Asphalt resurfacing", quantity: 1, unit: "project" },
      ],
    },
    // RFP — Q&A Open + Submissions
    {
      id: "rfp-1",
      type: "RFP",
      title: "Enterprise ERP Implementation",
      description: "Full RFP for ERP system selection and implementation partner.",
      status: "open",
      buyerId: "buyer-1",
      createdAt: daysAgo(21),
      updatedAt: daysAgo(7),
      dueDate: daysFromNow(21),
      publishedAt: daysAgo(7),
      sections: [
        { id: "sec-1", title: "Company Overview & Experience", description: "Provide company background and client references.", required: true },
        { id: "sec-2", title: "Technical Approach", description: "Describe architecture and deployment methodology.", required: true },
        { id: "sec-3", title: "Project Timeline & Milestones", description: "Provide a detailed project plan.", required: true },
        { id: "sec-4", title: "Pricing & Licensing", description: "Itemize licensing and implementation costs.", required: true },
        { id: "sec-5", title: "Change Management Plan", description: "Outline training and adoption strategies.", required: false },
      ],
      scoringCriteria: [
        { id: "crit-1", name: "Technical Fit", description: "Alignment with requirements", maxPoints: 30, weight: 30 },
        { id: "crit-2", name: "Implementation Experience", description: "Relevant project experience", maxPoints: 25, weight: 25 },
        { id: "crit-3", name: "Cost Competitiveness", description: "Total cost of ownership", maxPoints: 25, weight: 25 },
        { id: "crit-4", name: "Project Plan Quality", description: "Timeline realism", maxPoints: 20, weight: 20 },
      ],
    },
    // RFP — Closed (was awarded)
    {
      id: "rfp-2",
      type: "RFP",
      title: "Managed Security Services",
      description: "RFP for 24/7 managed security operations center.",
      status: "closed",
      buyerId: "buyer-2",
      createdAt: daysAgo(90),
      updatedAt: daysAgo(10),
      dueDate: daysAgo(30),
      publishedAt: daysAgo(80),
      closedAt: daysAgo(10),
      awardedSupplierId: "supplier-1",
      awardNotes: "Superior SOC capabilities and competitive pricing.",
      sections: [
        { id: "sec-1", title: "SOC Capabilities", description: "Describe monitoring and response capabilities.", required: true },
        { id: "sec-2", title: "Pricing Model", description: "Provide pricing structure and SLA tiers.", required: true },
      ],
      scoringCriteria: [
        { id: "crit-1", name: "Detection Capability", description: "Threat detection capabilities", maxPoints: 40, weight: 40 },
        { id: "crit-2", name: "Cost", description: "Annual contract value", maxPoints: 30, weight: 30 },
        { id: "crit-3", name: "SLA Compliance", description: "Response time guarantees", maxPoints: 30, weight: 30 },
      ],
    },
    // RFP — Draft
    {
      id: "rfp-3",
      type: "RFP",
      title: "Marketing Agency Partnership",
      description: "Draft RFP for digital marketing agency selection.",
      status: "draft",
      buyerId: "buyer-3",
      createdAt: daysAgo(3),
      updatedAt: daysAgo(2),
      dueDate: daysFromNow(45),
      sections: [
        { id: "sec-1", title: "Agency Portfolio", description: "Showcase relevant campaigns and results.", required: true },
      ],
      scoringCriteria: [
        { id: "crit-1", name: "Creative Quality", description: "Portfolio quality", maxPoints: 50, weight: 50 },
        { id: "crit-2", name: "Pricing", description: "Fee structure competitiveness", maxPoints: 50, weight: 50 },
      ],
    },
    // RFP — Published
    {
      id: "rfp-4",
      type: "RFP",
      title: "HR Benefits Administration Platform",
      description: "Select a benefits administration platform for 2,000 employees.",
      status: "open",
      buyerId: "buyer-1",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(1),
      dueDate: daysFromNow(35),
      publishedAt: daysAgo(1),
      sections: [
        { id: "sec-1", title: "Platform Overview", description: "Describe your platform capabilities.", required: true },
        { id: "sec-2", title: "Implementation Plan", description: "Outline onboarding timeline.", required: true },
      ],
      scoringCriteria: [
        { id: "crit-1", name: "Feature Fit", description: "Benefits module coverage", maxPoints: 50, weight: 50 },
        { id: "crit-2", name: "Cost", description: "Per-employee pricing", maxPoints: 50, weight: 50 },
      ],
    },
    // RFP — Awarded
    {
      id: "rfp-5",
      type: "RFP",
      title: "Data Warehouse Modernization",
      description: "Cloud data warehouse migration and analytics platform.",
      status: "awarded",
      buyerId: "buyer-3",
      createdAt: daysAgo(50),
      updatedAt: daysAgo(5),
      dueDate: daysAgo(10),
      publishedAt: daysAgo(45),
      awardedSupplierId: "supplier-6",
      awardNotes: "Strong cloud migration track record.",
      sections: [
        { id: "sec-1", title: "Migration Approach", description: "Describe migration methodology.", required: true },
      ],
      scoringCriteria: [
        { id: "crit-1", name: "Technical Approach", description: "Migration strategy quality", maxPoints: 60, weight: 60 },
        { id: "crit-2", name: "Cost", description: "Total project cost", maxPoints: 40, weight: 40 },
      ],
    },
    // RFP — Originated from RFI (converted example)
    {
      id: "rfp-6",
      type: "RFP",
      title: "Office Furniture Vendor Discovery (RFP)",
      description: "Initial market research for ergonomic office furniture suppliers.",
      status: "open",
      buyerId: "buyer-2",
      createdAt: daysAgo(4),
      updatedAt: daysAgo(4),
      dueDate: daysFromNow(26),
      publishedAt: daysAgo(4),
      linkedFromRfiId: "rfi-2",
      sections: [
        { id: "sec-1", title: "Requirement 1", description: "What product lines do you offer for enterprise offices?", required: true },
        { id: "sec-2", title: "Requirement 2", description: "What is your typical lead time for bulk orders?", required: true },
      ],
      scoringCriteria: [
        { id: "crit-1", name: "Overall Fit", description: "Alignment with RFI requirements", maxPoints: 50, weight: 50 },
        { id: "crit-2", name: "Cost", description: "Total cost competitiveness", maxPoints: 50, weight: 50 },
      ],
    },
  ],
  invitations: [
    { id: "inv-1", rfxId: "rfi-1", supplierType: "internal", supplierId: "supplier-1", status: "accepted", invitedAt: daysAgo(10), respondedAt: daysAgo(9) },
    { id: "inv-2", rfxId: "rfi-1", supplierType: "internal", supplierId: "supplier-2", status: "accepted", invitedAt: daysAgo(10), respondedAt: daysAgo(8) },
    { id: "inv-3", rfxId: "rfi-1", supplierType: "internal", supplierId: "supplier-3", status: "pending", invitedAt: daysAgo(10) },
    { id: "inv-4", rfxId: "rfi-2", supplierType: "internal", supplierId: "supplier-1", status: "accepted", invitedAt: daysAgo(40), respondedAt: daysAgo(38) },
    { id: "inv-5", rfxId: "rfi-2", supplierType: "internal", supplierId: "supplier-2", status: "accepted", invitedAt: daysAgo(40), respondedAt: daysAgo(39) },
    { id: "inv-8", rfxId: "rfi-5", supplierType: "internal", supplierId: "supplier-1", status: "accepted", invitedAt: daysAgo(15), respondedAt: daysAgo(14) },
    { id: "inv-9", rfxId: "rfi-5", supplierType: "internal", supplierId: "supplier-7", status: "accepted", invitedAt: daysAgo(15), respondedAt: daysAgo(13) },
    { id: "inv-10", rfxId: "rfq-1", supplierType: "internal", supplierId: "supplier-1", status: "accepted", invitedAt: daysAgo(5), respondedAt: daysAgo(4) },
    { id: "inv-11", rfxId: "rfq-1", supplierType: "internal", supplierId: "supplier-2", status: "accepted", invitedAt: daysAgo(5), respondedAt: daysAgo(3) },
    { id: "inv-12", rfxId: "rfq-1", supplierType: "internal", supplierId: "supplier-3", status: "pending", invitedAt: daysAgo(5) },
    { id: "inv-13", rfxId: "rfq-4", supplierType: "internal", supplierId: "supplier-6", status: "accepted", invitedAt: daysAgo(1), respondedAt: daysAgo(1) },
    { id: "inv-14", rfxId: "rfq-4", supplierType: "internal", supplierId: "supplier-7", status: "pending", invitedAt: daysAgo(1) },
    { id: "inv-ext-1", rfxId: "rfq-4", supplierType: "external", externalContact: { name: "Taylor Nguyen", email: "taylor@vendorpro.com", company: "VendorPro Inc" }, status: "pending", invitedAt: daysAgo(1) },
    { id: "inv-15", rfxId: "rfq-5", supplierType: "internal", supplierId: "supplier-4", status: "accepted", invitedAt: daysAgo(8), respondedAt: daysAgo(7) },
    { id: "inv-16", rfxId: "rfq-5", supplierType: "internal", supplierId: "supplier-5", status: "accepted", invitedAt: daysAgo(8), respondedAt: daysAgo(6) },
    { id: "inv-17", rfxId: "rfp-1", supplierType: "internal", supplierId: "supplier-1", status: "accepted", invitedAt: daysAgo(7), respondedAt: daysAgo(6) },
    { id: "inv-18", rfxId: "rfp-1", supplierType: "internal", supplierId: "supplier-2", status: "accepted", invitedAt: daysAgo(7), respondedAt: daysAgo(5) },
    { id: "inv-19", rfxId: "rfp-1", supplierType: "internal", supplierId: "supplier-3", status: "pending", invitedAt: daysAgo(7) },
    { id: "inv-20", rfxId: "rfp-4", supplierType: "internal", supplierId: "supplier-6", status: "pending", invitedAt: daysAgo(1) },
    { id: "inv-21", rfxId: "rfp-4", supplierType: "internal", supplierId: "supplier-8", status: "pending", invitedAt: daysAgo(1) },
    { id: "inv-22", rfxId: "rfp-6", supplierType: "internal", supplierId: "supplier-1", status: "accepted", invitedAt: daysAgo(4), respondedAt: daysAgo(3) },
    { id: "inv-23", rfxId: "rfp-6", supplierType: "internal", supplierId: "supplier-2", status: "accepted", invitedAt: daysAgo(4), respondedAt: daysAgo(3) },
  ],
  qaThreads: [
    { id: "qa-1", rfxId: "rfp-1", supplierId: "supplier-1", question: "Can we propose a phased rollout starting with the finance module?", askedAt: daysAgo(4), answer: "Yes, phased rollouts are acceptable. Please detail the phasing in your timeline section.", answeredAt: daysAgo(3), isPublic: true },
    { id: "qa-2", rfxId: "rfp-1", supplierId: "supplier-2", question: "Is on-premise deployment an option?", askedAt: daysAgo(2), isPublic: true },
    { id: "qa-3", rfxId: "rfq-1", supplierId: "supplier-1", question: "Are alternative laptop models acceptable if specs are met?", askedAt: daysAgo(3), answer: "Yes, equivalent or better specs are acceptable.", answeredAt: daysAgo(2), isPublic: true },
    { id: "qa-4", rfxId: "rfi-1", supplierId: "supplier-2", question: "Is FedRAMP certification required or preferred?", askedAt: daysAgo(1), isPublic: true },
    { id: "qa-5", rfxId: "rfq-5", supplierId: "supplier-4", question: "Can we propose a mix of jacket sizes rather than one size?", askedAt: daysAgo(2), isPublic: true },
  ],
  submissions: [
    { id: "sub-1", rfxId: "rfi-1", supplierId: "supplier-1", status: "submitted", submittedAt: daysAgo(5), updatedAt: daysAgo(5), rfiAnswers: [
      { questionId: "q1", value: "Multi-region AWS and Azure deployment with 12 global data centers." },
      { questionId: "q2", value: "SOC 2 Type II, ISO 27001, FedRAMP Moderate" },
      { questionId: "q3", value: "Yes" },
      { questionId: "q4", value: "Completed 5 enterprise migrations totaling 2,500+ VMs." },
    ]},
    { id: "sub-2", rfxId: "rfi-1", supplierId: "supplier-2", status: "draft", updatedAt: daysAgo(2), rfiAnswers: [
      { questionId: "q1", value: "Hybrid cloud with on-premise and GCP regions." },
    ]},
    { id: "sub-3", rfxId: "rfi-2", supplierId: "supplier-1", status: "submitted", submittedAt: daysAgo(15), updatedAt: daysAgo(15), rfiAnswers: [
      { questionId: "q1", value: "Full ergonomic furniture line including sit-stand desks." },
      { questionId: "q2", value: "4-6 weeks for orders over 100 units." },
    ]},
    { id: "sub-4", rfxId: "rfi-5", supplierId: "supplier-1", status: "submitted", submittedAt: daysAgo(5), updatedAt: daysAgo(5), rfiAnswers: [
      { questionId: "q1", value: "HP Managed Print Services and Xerox DocuShare." },
      { questionId: "q2", value: "Yes" },
    ]},
    { id: "sub-5", rfxId: "rfi-5", supplierId: "supplier-7", status: "submitted", submittedAt: daysAgo(4), updatedAt: daysAgo(4), rfiAnswers: [
      { questionId: "q1", value: "Canon uniFLOW and Papercut MF." },
      { questionId: "q2", value: "Yes, nationwide coverage." },
    ]},
    { id: "sub-6", rfxId: "rfq-1", supplierId: "supplier-1", status: "submitted", submittedAt: daysAgo(2), updatedAt: daysAgo(2), rfqQuotes: [
      { lineItemId: "li-1", unitPrice: 1150, notes: "Dell Latitude 5540" },
      { lineItemId: "li-2", unitPrice: 1750, notes: "Dell Latitude 7640" },
      { lineItemId: "li-3", unitPrice: 185 },
    ]},
    { id: "sub-7", rfxId: "rfq-1", supplierId: "supplier-2", status: "submitted", submittedAt: daysAgo(1), updatedAt: daysAgo(1), rfqQuotes: [
      { lineItemId: "li-1", unitPrice: 1180 },
      { lineItemId: "li-2", unitPrice: 1820 },
      { lineItemId: "li-3", unitPrice: 195 },
    ]},
    { id: "sub-8", rfxId: "rfp-1", supplierId: "supplier-1", status: "submitted", submittedAt: daysAgo(1), updatedAt: daysAgo(1), rfpResponses: [
      { sectionId: "sec-1", content: "GlobalTech Solutions has 15 years of ERP implementation experience with 200+ enterprise clients." },
      { sectionId: "sec-2", content: "Cloud-native microservices architecture with API-first integration layer." },
      { sectionId: "sec-3", content: "18-month phased rollout: Finance (6mo), HR (4mo), Supply Chain (8mo)." },
      { sectionId: "sec-4", content: "Total 5-year TCO: $2.4M." },
      { sectionId: "sec-5", content: "Comprehensive change management with super-user network." },
    ], attachments: [{ id: "att-1", name: "proposal-v1.pdf" }]},
    { id: "sub-9", rfxId: "rfp-1", supplierId: "supplier-2", status: "draft", updatedAt: daysAgo(1), rfpResponses: [
      { sectionId: "sec-1", content: "Nexus Industries - 10 years ERP experience, 50+ clients." },
    ]},
  ],
  notifications: [
    { id: "notif-1", userId: "supplier-1", rfxId: "rfp-1", title: "New RFP Invitation", message: "You have been invited to respond to Enterprise ERP Implementation.", type: "info", read: true, createdAt: daysAgo(7) },
    { id: "notif-2", userId: "supplier-2", rfxId: "rfp-1", title: "Q&A Update", message: "Your question about on-premise deployment is awaiting an answer.", type: "info", read: false, createdAt: daysAgo(2) },
    { id: "notif-3", userId: "supplier-3", rfxId: "rfq-1", title: "RFQ Invitation", message: "You have been invited to submit a quote for Q2 Laptop Procurement.", type: "info", read: false, createdAt: daysAgo(5) },
    { id: "notif-4", userId: "supplier-3", rfxId: "rfq-2", title: "Contract Awarded!", message: "Congratulations! You have been awarded the Office Cleaning Services contract.", type: "award", read: true, createdAt: daysAgo(3) },
    { id: "notif-5", userId: "buyer-1", rfxId: "rfp-1", title: "New Submission", message: "GlobalTech Solutions submitted their RFP response.", type: "success", read: false, createdAt: daysAgo(1) },
    { id: "notif-6", userId: "buyer-2", rfxId: "rfi-1", title: "New Q&A Question", message: "A supplier asked a question on Cloud Infrastructure Capabilities Assessment.", type: "info", read: false, createdAt: daysAgo(1) },
    { id: "notif-7", userId: "buyer-3", rfxId: "rfq-5", title: "New Q&A Question", message: "A supplier asked a question on Uniform & Apparel Supply.", type: "info", read: false, createdAt: daysAgo(2) },
    { id: "notif-8", userId: "buyer-1", rfxId: "rfq-1", title: "New Submission", message: "Nexus Industries submitted their RFQ response.", type: "success", read: false, createdAt: daysAgo(1) },
  ],
  activityLog: [
    { id: "act-1", rfxId: "rfp-1", userId: "buyer-1", action: "Created RFP", details: "Enterprise ERP Implementation RFP created", createdAt: daysAgo(21) },
    { id: "act-2", rfxId: "rfp-1", userId: "buyer-1", action: "Published", details: "RFP published and invitations sent to 3 suppliers", createdAt: daysAgo(7) },
    { id: "act-3", rfxId: "rfp-1", userId: "supplier-1", action: "Submitted Response", details: "GlobalTech Solutions submitted proposal", createdAt: daysAgo(1) },
    { id: "act-4", rfxId: "rfi-1", userId: "buyer-1", action: "Published", details: "RFI published to 3 suppliers", createdAt: daysAgo(10) },
    { id: "act-5", rfxId: "rfq-2", userId: "buyer-2", action: "Awarded", details: "Contract awarded to Brightline Systems", createdAt: daysAgo(3) },
    { id: "act-6", rfxId: "rfi-2", userId: "buyer-2", action: "Closed RFI", details: "Review complete. GlobalTech and Nexus shortlisted.", createdAt: daysAgo(5) },
    { id: "act-7", rfxId: "rfp-6", userId: "buyer-2", action: "Converted to RFP", details: "Created from RFI Office Furniture Vendor Discovery", createdAt: daysAgo(4) },
    { id: "act-8", rfxId: "rfq-1", userId: "buyer-1", action: "Published", details: "RFQ published to 3 suppliers", createdAt: daysAgo(5) },
    { id: "act-9", rfxId: "rfi-5", userId: "buyer-2", action: "Published", details: "RFI published to 2 suppliers", createdAt: daysAgo(15) },
    { id: "act-10", rfxId: "rfp-5", userId: "buyer-3", action: "Awarded", details: "Awarded to Meridian Tech", createdAt: daysAgo(5) },
  ],
};
